services:
  soil_humidity_reader:
    build:
      context: ./soil_humidity_reader
    container_name: soil_humidity_reader
    privileged: true
    ports:
      - "8000:8000"
    restart: unless-stopped

  air_monitoring_service:
    build:
      context: ./air_monitoring_service
    container_name: air_monitoring_service
    privileged: true
    ports:
      - "8001:8001"
    restart: unless-stopped

  weather_reader:
    build:
      context: ./weather_reader
    container_name: weather_reader
    ports:
      - "8002:8002"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=90d'
      - '--storage.tsdb.retention.size=15GB'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-pyroscope-app
    restart: unless-stopped

volumes:
  grafana-data:
  prometheus-data:
